name: cs236781-hw
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.8.12
  - ipython
  - jupyter
  - jupyterlab
  - nodejs>=12.0
  - pip
  - pytest
  - pytest-xdist
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - tqdm
  - pytorch=1.10.1
  - mkl<2022        # prevents crash when importing torch on M1 mac via rosetta2
  - torchvision=0.11.2
  - cudatoolkit=11.3
  - torchtext

  - pip:
      - nbmerge
      - ultralytics
      - seaborn
      - opencv-python
      - pyyaml
      - requests

platforms:
  - linux-64