name: guy
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - numpy=1.21
  - pandas
  - matplotlib
  - ipython
  - jupyterlab
  - tqdm
  - scikit-learn
  - scipy
  - swig
  - ffmpeg
  - nodejs
  - pytest
  - pytest-xdist

  # PyTorch with CUDA 11.3 (compatible with Windows)
  - pytorch=1.10
  - torchvision=0.11
  - cudatoolkit=11.3

  - pip
  - pip:
      - nbmerge
      - gym[atari,accept-rom-license,box2d]==0.21.0
